// Code generated by Icestudio 0.11.3w202402070902202402070902202402070902202402070902202402070902

`default_nettype none

//---- Top entity
module main (
 input vclk,
 output v549dbe
);
 wire w0;
 wire w1;
 assign v549dbe = w0;
 assign w1 = vclk;
 vadcbe7 v55fb83 (
  .v2efea4(w0),
  .v0daa9e(w1)
 );
endmodule

//---- Top entity
module vadcbe7 #(
 parameter v245bef = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p1 = v245bef;
 wire w0;
 wire w2;
 assign w0 = v0daa9e;
 assign v2efea4 = w2;
 v435b29 #(
  .v100e1b(p1)
 ) v81886f (
  .v0daa9e(w0),
  .v2efea4(w2)
 );
endmodule

//---------------------------------------------------
//-- Prescaler22
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 22-bits prescaler
//---------------------------------------------------
//---- Top entity
module v435b29 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v435b29_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v435b29_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
